version: "3"

services:

  database-dcf:
    image: postgres:alpine
    container_name: database-dcf
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dcf
    volumes:
      - database-dcf:/var/lib/postgresql/data

  backend-dcf:
    build: services/backend
    container_name: backend-dcf
    environment:
      - DJANGO_DB_ENGINE=django.db.backends.postgresql
      - DJANGO_DB_NAME=dcf
      - DJANGO_DB_USER=user
      - DJANGO_DB_PASSWORD=password
      - DJANGO_DB_HOST=database-dcf
      - DJANGO_DB_PORT=5432
    volumes:
      - ./services/backend/code:/code
    depends_on:
      - database-dcf
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  database-dcf:
