version: "3"

services:

  database-dcf:
    image: postgres:alpine
    container_name: database-dcf
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dcf
    volumes:
      - database-dcf:/var/lib/postgresql/data

  backend-dcf:
    build: services/backend
    container_name: backend-dcf
    environment:
      - CELERY_BROKER_URL=redis://redis-dcf:6379
      - CELERY_RESULT_BACKEND=redis://redis-dcf:6379
      - DJANGO_DB_ENGINE=django.db.backends.postgresql
      - DJANGO_DB_NAME=dcf
      - DJANGO_DB_USER=user
      - DJANGO_DB_PASSWORD=password
      - DJANGO_DB_HOST=database-dcf
      - DJANGO_DB_PORT=5432
    volumes:
      - ./services/backend/code:/code
    depends_on:
      - database-dcf
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000

  backend-worker-dcf:
    build: services/backend
    container_name: backend-worker-dcf
    environment:
      - CELERY_BROKER_URL=redis://redis-dcf:6379
      - CELERY_RESULT_BACKEND=redis://redis-dcf:6379
      - DJANGO_DB_ENGINE=django.db.backends.postgresql
      - DJANGO_DB_NAME=dcf
      - DJANGO_DB_USER=user
      - DJANGO_DB_PASSWORD=password
      - DJANGO_DB_HOST=database-dcf
      - DJANGO_DB_PORT=5432
    volumes:
      - ./services/backend/code:/code
    depends_on:
      - database-dcf
    # Concurrency is forced to 1 in order to easily create queue of tasks
    command: celery --app dcf worker --concurrency=1 -Ofair -l info 

  redis-dcf:
    image: redis:6.0.8-alpine
    container_name: redis-dcf

  flower:  
    image: mher/flower:0.9.7
    container_name: flower
    environment:
      - CELERY_BROKER_URL=redis://redis-dcf:6379/0
      - FLOWER_PORT=8888
    # command: --url_prefix=flower
    ports:  
      - 8888:8888

volumes:
  database-dcf:
