# Generated by Django 3.2.11 on 2022-01-12 10:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeavyComputation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=36, verbose_name='Name')),
                ('status', models.CharField(blank=True, choices=[('Initialized', 'Initialized'), ('Scheduled', 'Scheduled'), ('Computing', 'Computing'), ('Computed', 'Computed'), ('Frozen', 'Frozen'), ('Error', 'Error')], default='Initialized', max_length=36, verbose_name='Status')),
            ],
        ),
    ]
