# Generated by Django 3.2.11 on 2022-01-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heavyComputation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heavycomputation',
            name='task_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
