# Generated by Django 3.2.11 on 2022-01-27 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heavyComputation', '0002_heavycomputation_task_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heavycomputation',
            name='task_uuid',
        ),
    ]
